services:
#  banking-service:
#    image: joao0212/banking-service:v1
#    container_name: banking-service-container
#    environment:
#      - QUARKUS_CLIENT_HTTP=host.docker.internal
#      - QUARKUS_CLIENT_HTTP_PORT=8181
#      - QUARKUS_DATASOURCE_USERNAME=rafael
#      - QUARKUS_DATASOURCE_PASSWORD=rafael
#      - QUARKUS_DATASOURCE_HOST=postgres-db-banking-service
#      - QUARKUS_DATASOURCE_PORT=5432
#    ports:
#      - 8080:8080
#    depends_on:
#      - postgres-db-banking-service

  postgres-db-banking-service:
    image: postgres:14
    container_name: postgres-db-banking-service-container
    environment:
      - POSTGRES_USER=rafael
      - POSTGRES_PASSWORD=rafael
      - POSTGRES_DB=agencia
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"


  otel-collector:
    image: otel/opentelemetry-collector:0.146.1
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "4317:4317" # OTLP gRPC receiver


  jaeger:
    image: jaegertracing/all-in-one:1.76
    ports:
      - "16686:16686" # UI
      - "14250:14250" # gRPC
      - "14268:14268" # HTTP Ingest
      - "6831:6831/udp" # UDP (Thrift compact)

volumes:
  postgres_data:
    driver: local

